image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\DeviceIOControlLib\DeviceIOControlLib.csproj)

    [string]$version = $doc.Project.PropertyGroup.VersionPrefix
    
    Update-AppveyorBuild -Version "$($version.Trim()).$env:APPVEYOR_BUILD_NUMBER"
- ps: # Library
- ps: msbuild /t:Build /p:Configuration=Release DeviceIOControlLib
- ps: # Pack Library
- ps: msbuild /t:Pack /p:Configuration=Release DeviceIOControlLib
- ps: # Utilities
- ps: msbuild /t:Build /p:Configuration=Release DemoApplication
install:
- msbuild /t:Restore
artifacts:
- path: DeviceIOControlLib\bin\Release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget